[package]
name = "rnote-compose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnote-fileformats = {path = "../rnote-fileformats", version="0.1"}

log = "0.4.16"
pretty_env_logger = "0.4.0"
anyhow = "1.0"
serde = {version = "1.0", features = ["derive"]}
rand = "0.8.5"
rand_pcg = "0.3.1"
rand_distr = "0.4.3"
regex = "1.5"
chrono = {version ="0.4.19", features = ["serde"] }
nalgebra = { version = "0.30.1", features = ["serde-serialize"] }
parry2d-f64 = { version = "0.8.0", features = ["serde-serialize"] }
kurbo = {version = "0.8.2", features = ["serde"] }
piet = { path = "../piet/piet", features = ["serde"]}
piet-svg = { path = "../piet/piet-svg"}
image = "0.23.14"
svg = "0.10.0"

[dev-dependencies]