on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

name: CI

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    container: fedora:37
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo dnf upgrade --refresh -y
          sudo dnf install -y gcc gcc-c++ clang make cmake meson kernel-devel gtk4-devel libadwaita-devel poppler-glib-devel poppler-data alsa-lib-devel libappstream-glib desktop-file-utils
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            _mesonbuild/cargo-home/bin/
            _mesonbuild/cargo-home/registry/index/
            _mesonbuild/cargo-home/registry/cache/
            _mesonbuild/cargo-home/git/db/
            _mesonbuild/target/
          key: cargo-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}
      - name: Configure
        run: |
          meson setup --prefix=/usr _mesonbuild
          meson configure -Dprofile=devel -Dcli=true _mesonbuild
      - name: Run cargo fmt
        run: meson compile cargo-fmt-check -C _mesonbuild
      - name: Check app
        run: meson compile app-cargo-check -C _mesonbuild
      - name: Check CLI
        run: meson compile cli-cargo-check -C _mesonbuild
      - name: Compile
        run: meson compile -v -C _mesonbuild
      - name: Install
        run: meson install -v -C _mesonbuild
      - name: Run tests
        run: meson test -v -C _mesonbuild
      - name: Run clippy for app
        run: meson compile app-cargo-clippy -C _mesonbuild
        continue-on-error: true
      - name: Run clippy for CLI
        run: meson compile cli-cargo-clippy -C _mesonbuild
        continue-on-error: true
      - name: Run file compatibility tests
        run: |
          rnote_cli test\
            misc/screenshots-pages/main_window.rnote\
            misc/screenshots-pages/pdf_annotation.rnote\
            misc/screenshots-pages/lecture_note_1.rnote\
            misc/screenshots-pages/lecture_note_2.rnote